library(survival)
library(survminer)
library(dplyr)
library(ggsurvey)
library(svglite)
setwd("G:/Arbeit")
data<-read.csv(file="survival.csv",sep = ";")
data$Genotype<-as.factor(data$Genotype)
surv_object <- Surv(time = data$Lifespan, event = data$Endpoint)
fit1<-survfit(surv_object ~ Genotype, data = data)
survp<-ggsurvplot(fit1, data = data, censor=FALSE)
ggsave("survplot.svg", survp$plot, height = 4, width = 4)
survdiff(surv_object ~ Genotype, data = data)
