library(survival)
library(survminer)
library(dplyr)
library(ggsurvey)
library(svglite)
library(readxl)
setwd("D:/Peter/Analysis/KCNA2/P405L_Mice/Phenomaster")
data<-read_xlsx("survival_P405L_20230612.xlsx")
data$Genotype<-as.factor(data$Genotype)
data<-data[data$Genotype %in% c("C57Bl/6","F1","F2","F3"),]
surv_object <- Surv(time = data$Lifespan, event = data$Endpoint)
fit1<-survfit(surv_object ~ Genotype, data = data)
survp<-ggsurvplot(fit1, data = data, censor=T)
ggsave("survplot.svg", survp$plot, height = 4, width = 4)
survdiff(surv_object ~ Genotype, data = data)
